apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: frontend-container
          image: fatimadiao20/image-front
          ports:
            - containerPort: 5173  # ✅ Le vrai port écouté dans ton conteneur
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front-app
  ports:
    - port: 80         # ✅ Port exposé par le service
      targetPort: 80 # ✅ Port utilisé par le conteneur
      nodePort: 30517
