apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1  # Recommended to explicitly set replicas
  selector:
    matchLabels:
      app: postgres  # Must match the template's labels
  template:
    metadata:
      labels:
        app: postgres  # This must match the selector
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - secretRef:
            name: postgres-credentials
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc  # Make sure this PVC exists

---
# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
