apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z database 5432; do echo "Waiting for postgres..."; sleep 2; done;']
      containers:
        - name: backend
          image: fatimadiao20/image-back
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "odc.settings"
            - name: POSTGRES_HOST
              value: "database"
            - name: POSTGRES_DB
              value: "odcdb"
            - name: POSTGRES_USER
              value: "odc"
            - name: POSTGRES_PASSWORD
              value: "odc123"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30002
